[project]
name = "graph-slam"
version = "0.1.0"
description = "An implementation of Factor Graph SLAM backend algorithm"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "scipy>=1.15.2",
]
